name: GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - "website/**"
      - ".github/workflows/gh-pages.yml"
jobs:
  build-and-deploy:
    name: Build use-nft and deploy the website
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build use-nft
        run: yarn install --immutable && yarn build --noStats

      - name: Build website/
        env:
          VITE_INFURA_KEY: ${{ secrets.INFURA_KEY }}
        run: cd website && yarn install --immutable && yarn build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: gh-pages
          folder: website/dist
