name: GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - 'demo/**'
      - '.github/workflows/gh-pages.yml'
jobs:
  build-and-deploy:
    name: Build use-nft and deploy the website
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build use-nft
        run: yarn install --immutable && yarn build

      - name: Build demo/
        run: cd demo && yarn install --immutable && rm -rf ./node_modules/use-nft/node_modules && yarn build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: gh-pages
          folder: demo/dist
